In [2]:
import numpy as np

In [3]:
v_hor_np = np.array([1, 2])
print(v_hor_np )

[1 2]


In [4]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [5]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
diag = np.diag(m_sqr_mx)
print(diag)
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [7]:
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [9]:
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


In [12]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)

[[ 9  7  8]
 [14 11 19]]


In [13]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')
C = A.dot(B)
print(C)

[[31 19]
 [85 55]]


In [20]:
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

4


In [23]:
m_eye[3][3] = 0
rank = np.linalg.matrix_rank(m_eye)
print(rank)


3
