# Транспонирование матрицы

Свойство 1 дважды транспонированная матрица равна исходной матрице:

$ (A^T)^T = A$

In [2]:
import numpy as np
A = np.matrix('4 2 7; 4 5 6; 1 1 1')
print(A)
R = (A.T).T
print(R)

[[4 2 7]
 [4 5 6]
 [1 1 1]]
[[4 2 7]
 [4 5 6]
 [1 1 1]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

$ (A + B)^T = A^T + B^T $

In [3]:
B = np.matrix('7 8 9; 0 7 5; 3 3 3')
L = (A + B).T
R = A.T + B.T
print(L)
print(R)

[[11  4  4]
 [10 12  4]
 [16 11  4]]
[[11  4  4]
 [10 12  4]
 [16 11  4]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

$ (AB)^T = B^T * A^T $

In [4]:
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)
print(R)

[[49 46 10]
 [67 85 18]
 [67 79 17]]
[[49 46 10]
 [67 85 18]
 [67 79 17]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

$ (kA)^T = kA^T $


In [6]:
k = 7
L = (k * A).T
R = k * (A.T)
print(L)
print(R)

[[28 28  7]
 [14 35  7]
 [49 42  7]]
[[28 28  7]
 [14 35  7]
 [49 42  7]]


Свойство 5. Определители исходной и транспонированной матрицы совпадают:

$ |A| = |A^T |$

In [7]:
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))
print(format(A_T_det, '.9g'))

-7
-7


# Действия над матрицами.
# Умножение матрицы на число

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

$ 1 * A = A$

In [8]:
print(A)
L = 1 * A
print(L)


[[4 2 7]
 [4 5 6]
 [1 1 1]]
[[4 2 7]
 [4 5 6]
 [1 1 1]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:

$ 0 * A = Z $

In [9]:
print(A)
L = 0 * A
print(L)

[[4 2 7]
 [4 5 6]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел:

$ (a + b) * A = a * A + b * A $

In [10]:
print(A)
q = 137
p = 3
L = (p + q) * A
R = p * A + q * A
print(L)
print(R)

[[4 2 7]
 [4 5 6]
 [1 1 1]]
[[560 280 980]
 [560 700 840]
 [140 140 140]]
[[560 280 980]
 [560 700 840]
 [140 140 140]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

$ (a * b) * A = a * (b * A) $

In [11]:
q = 4
p = 22
L = (p * q) * A
R = p * (q * A)
print(L)
print(R)

[[352 176 616]
 [352 440 528]
 [ 88  88  88]]
[[352 176 616]
 [352 440 528]
 [ 88  88  88]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

$ k * (A + B = k * A + k * B $

In [12]:
k = 7
L = k * (A + B)
R = k * A + k * B
print(L)
print(R)

[[ 77  70 112]
 [ 28  84  77]
 [ 28  28  28]]
[[ 77  70 112]
 [ 28  84  77]
 [ 28  28  28]]


# Сложение матриц

Складывать можно только матрицы одинаковой размерности — то есть матрицы, у которых
совпадает количество столбцов и строк.

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

$ A + B = B + A $

In [13]:
L = A + B
R = B + A
print(L)
print(R)

[[11 10 16]
 [ 4 12 11]
 [ 4  4  4]]
[[11 10 16]
 [ 4 12 11]
 [ 4  4  4]]


Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от
порядка, в котором эта операция будет выполняться:

$ A + (B + C) = (A + B) + C $ 

In [14]:
C = np.matrix('33 22 11; 44 55 66; 77 99 88')
R = (A + B) + C
L = A + (B + C)
print(R)
print(L)

[[ 44  32  27]
 [ 48  67  77]
 [ 81 103  92]]
[[ 44  32  27]
 [ 48  67  77]
 [ 81 103  92]]


Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является
нулевой матрицей :

$ A + (-A) = Z $

In [15]:
L = A + (-1)*A
print(L)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# Умножение матриц

Умножать можно только матрицы, отвечающие следующему требованию: количество столбцов
первой матрицы должно быть равно числу строк второй матрицы.

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в
котором будет выполняться эта операция:

$ A * (B * C) = (A * B) * C $

In [17]:
A = np.matrix('1 2 3; 4 5 6; 7 8 9')
B = np.matrix('5 2 4; 7 4 7; 2 2 2')
C = np.matrix('66 55 44; 11 22 33; 99 99 0')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[ 4202  4103  1628]
 [11099 10802  4268]
 [17996 17501  6908]]
[[ 4202  4103  1628]
 [11099 10802  4268]
 [17996 17501  6908]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно
сумме произведений матриц:

$ A * (B + C) = A * B + A * C $

In [19]:
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)
print(R)

[[ 410  412  134]
 [ 980  964  404]
 [1550 1516  674]]
[[ 410  412  134]
 [ 980  964  404]
 [1550 1516  674]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не
выполняется правило независимости произведения от перестановки множителей:
    
$ A * B ≠ B * A $

In [21]:
L = A.dot(B)
R = B.dot(A)
print(L)
print(R)

[[ 25  16  24]
 [ 67  40  63]
 [109  64 102]]
[[ 41  52  63]
 [ 72  90 108]
 [ 24  30  36]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

$ E * A = A * E = A $

In [23]:
A = np.matrix('1 2; 3 4')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)
print(R)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

$ Z * A = A * Z = Z$

In [25]:
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print(L)
print(R)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


# Определитель матрицы

Определитель матрицы размера (n-го порядка) является одной из ее численных характеристик.
Определитель матрицы A обозначается как |A| или det(A), его также называют детерминантом.

Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

$ det(A) = det(A^T) $

In [28]:
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)
print(det_A_t)

-2.0
-2.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [29]:
A = np.matrix('5 3 1; 0 0 0; 55 28 9')
print(A)
np.linalg.det(A)

[[ 5  3  1]
 [ 0  0  0]
 [55 28  9]]


0.0

Свойство 3. При перестановке строк матрицы знак ее определителя меняется на
противоположный:
    
$ det(A) = -det(A') $

In [36]:
A = np.matrix('11 2 8; 44 3 66; 77 4 99')
print(A)
B = np.matrix('44 3 66; 11 2 8; 77 4 99')
print(B)

[[11  2  8]
 [44  3 66]
 [77  4 99]]
[[44  3 66]
 [11  2  8]
 [77  4 99]]


In [38]:
round(np.linalg.det(A), 3)

1375.0

In [39]:
round(np.linalg.det(B), 3)

-1375.0

Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [40]:
A = np.matrix('11 2 8; 44 3 66; 11 2 8')
print(A)
np.linalg.det(A)

[[11  2  8]
 [44  3 66]
 [11  2  8]]


0.0

Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и
определитель будет умножен на это число:

In [47]:
A = np.matrix('1 5 8; 4 3 26; 11 2 4')
np.linalg.det(A)

1110.0

In [49]:
B = A.copy()
k = 3
B[2, :] = k * B[2, :]
np.linalg.det(B)

3330.000000000004

Свойство 6. Если к элементам одной строки прибавить элементы другой строки, умноженные на
одно и тоже число, то определитель матрицы не изменится:

In [50]:
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)
print(B)

[[ 1  5  8]
 [ 4  3 26]
 [11  2  4]]
[[ 1  5  8]
 [ 7 18 50]
 [11  2  4]]


In [51]:
np.linalg.det(A)

1110.0

In [52]:
np.linalg.det(B)

1110.0

Свойство 7. Если строка или столбец матрицы является линейной комбинацией других строк
(столбцов), то определитель такой матрицы равен нулю:


In [56]:
A = np.matrix('3 4 5; 6 5 1; -3 -1 -4')
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

0.0

Свойство 8. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [58]:
print(A)
A[1, :] = k * A[0, :]
round(np.linalg.det(A), 3)

[[ 3  4  5]
 [ 6  8 10]
 [-3 -1 -4]]


0.0

# Обратная матрица

Обратной матрицей матрицы называют матрицу, удовлетворяющую следующему
равенству:

$ A * A^-1 = A^-1 * A = E $

Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

$ (A^-1)^-1 = A $

In [60]:
A = np.matrix('2 2; 1 3')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)
print(A_inv_inv)

[[2 2]
 [1 3]]
[[2. 2.]
 [1. 3.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице
от обратной матрицы:

$ (A^T)^-1 = (A^-1)^T $

In [61]:
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)
print(R)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]
[[ 0.75 -0.25]
 [-0.5   0.5 ]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

$ (A1 * A2)^-1 = A2^-1 * A1 ^-1 $

In [63]:
A = np.matrix('2 2; 1 3')
B = np.matrix('11 1; 2 22')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)
print(R)

[[ 0.06979167 -0.04791667]
 [-0.01770833  0.02708333]]
[[ 0.06979167 -0.04791667]
 [-0.01770833  0.02708333]]


# Ранг матрицы

Рангом называют
максимальное число линейно независимых строк (столбцов) матрицы. Линейная независимость
означает, что строки (столбцы) не могут быть линейно выражены через другие строки (столбцы).
Ранг матрицы можно найти через ее миноры, он равен наибольшему порядку минора, который не
равен нулю. Существование ранга у матрицы не зависит от того квадратная она или нет.

In [73]:
m = np.matrix('0 0; 1 3; 5 -1; -11 1')
print(m)
rank = np.linalg.matrix_rank(m)
print(rank)

[[  0   0]
 [  1   3]
 [  5  -1]
 [-11   1]]
2
